name: Next.js CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze Next.js Application

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Display Node Version
        shell: powershell
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        shell: powershell
        run: npm install

      - name: Build Application
        shell: powershell
        run: npm run build

      - name: Install Sonar Scanner
        shell: powershell
        run: npm install -g @sonar/scan

      - name: Verify SonarQube URL
        shell: powershell
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          Write-Host "SONAR_HOST_URL = $env:SONAR_HOST_URL"
          Invoke-WebRequest "$env:SONAR_HOST_URL/api/server/version"

      - name: SonarQube Scan
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar `
            -D"sonar.host.url=$env:SONAR_HOST_URL" `
            -D"sonar.token=$env:SONAR_TOKEN" `
            -D"sonar.projectKey=gocart"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next